package util;

import model.User;
import java.lang.reflect.Field;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.*;

/**
 *  1. Scans all fields of class T for @Column annotation via Reflection
 *  2. For each annotated field, reads the matching column from ResultSet
 *  3. Sets the field value directly (even private fields)
 *  4. Returns a fully populated T object — no manual mapping needed
 */
public class ReflectionMapper {

    // ── Cache ──────────────────────────────────────────────────────────────────
    // Map<Class, List<Field>> — avoids re-scanning annotations on every row
    private static final Map<Class<?>, List<Field>> fieldCache = new HashMap<>();

    // ── Core mapper ───────────────────────────────────────────────────────────
    /**
     * Maps one ResultSet row → one instance of class T.
     *
     * Generic <T>: call as:
     *   User u    = ReflectionMapper.map(rs, User.class);
     *   Course c  = ReflectionMapper.map(rs, Course.class);
     *
     * @param rs    ResultSet positioned at the current row
     * @param clazz the model class to instantiate
     * @return fully populated T object
     */
    public static <T> T map(ResultSet rs, Class<T> clazz) throws Exception {

        // 1. Create blank instance using default constructor
        T instance = clazz.getDeclaredConstructor().newInstance();

        // 2. Get cached (or scan) @Column fields for this class
        List<Field> fields = getAnnotatedFields(clazz);

        // 3. For each annotated field → read from ResultSet → set on instance
        for (Field field : fields) {
            User.Column col = field.getAnnotation(User.Column.class);
            if (col == null) continue;

            String columnName = col.name();
            field.setAccessible(true); // allow setting private fields

            try {
                Object value = readColumn(rs, columnName, field.getType());
                field.set(instance, value);
            } catch (SQLException e) {
                // Column might not be in this particular query — skip silently
            }
        }
        return instance;
    }

    // ── Map full ResultSet → List<T> ──────────────────────────────────────────
    /**
     * Maps all rows in a ResultSet to a List<T>.
     *
     * Usage:
     *   List<User> users = ReflectionMapper.mapList(rs, User.class);
     */
    public static <T> List<T> mapList(ResultSet rs, Class<T> clazz) throws Exception {
        List<T> list = new ArrayList<>();
        while (rs.next()) list.add(map(rs, clazz));
        return list;
    }

    // ── Auto-generate SELECT query via Reflection ──────────────────────────────
    /**
     * Builds "SELECT col1, col2, ... FROM tableName" using @Column annotations.
     *
     * Usage:
     *   String sql = ReflectionMapper.buildSelect(User.class, "users");
     *   → "SELECT id, name, email, password_hash, role, ... FROM users"
     */
    public static <T> String buildSelect(Class<T> clazz, String tableName) {
        List<Field> fields = getAnnotatedFields(clazz);
        List<String> columns = new ArrayList<>();
        for (Field f : fields) {
            User.Column col = f.getAnnotation(User.Column.class);
            if (col != null) columns.add(col.name());
        }
        return "SELECT " + String.join(", ", columns) + " FROM " + tableName;
    }

    /**
     * Builds "SELECT ... FROM tableName WHERE columnName = ?"
     */
    public static <T> String buildSelectWhere(Class<T> clazz, String tableName, String whereColumn) {
        return buildSelect(clazz, tableName) + " WHERE " + whereColumn + " = ?";
    }

    /**
     * Builds an INSERT statement from @Column annotations.
     * Skips "id" (auto-generated by DB).
     *
     * → "INSERT INTO users (name, email, ...) VALUES (?, ?, ...)"
     */
    public static <T> String buildInsert(Class<T> clazz, String tableName) {
        List<Field> fields = getAnnotatedFields(clazz);
        List<String> cols = new ArrayList<>();
        List<String> placeholders = new ArrayList<>();
        for (Field f : fields) {
            User.Column col = f.getAnnotation(User.Column.class);
            if (col != null && !col.name().equals("id")) {
                cols.add(col.name());
                placeholders.add("?");
            }
        }
        return "INSERT INTO " + tableName
                + " (" + String.join(", ", cols) + ")"
                + " VALUES (" + String.join(", ", placeholders) + ")";
    }

    // ── Extract values for INSERT ──────────────────────────────────────────────
    /**
     * Extracts field values from an object for use as PreparedStatement params.
     * Skips "id" field (DB auto-generates it).
     *
     * Usage:
     *   Object[] params = ReflectionMapper.extractValues(user);
     *   db.insert(ReflectionMapper.buildInsert(User.class, "users"), params);
     */
    public static <T> Object[] extractValues(T obj) throws Exception {
        List<Field> fields = getAnnotatedFields(obj.getClass());
        List<Object> values = new ArrayList<>();
        for (Field f : fields) {
            User.Column col = f.getAnnotation(User.Column.class);
            if (col != null && !col.name().equals("id")) {
                f.setAccessible(true);
                Object val = f.get(obj);
                // Convert enums to String for DB storage
                values.add(val instanceof Enum ? val.toString() : val);
            }
        }
        return values.toArray();
    }

    // ── Field cache ────────────────────────────────────────────────────────────
    /**
     * Returns annotated fields for a class, using cache to avoid repeat scanning.
     * Map<Class, List<Field>> = one scan per class, then cached forever.
     */
    private static List<Field> getAnnotatedFields(Class<?> clazz) {
        return fieldCache.computeIfAbsent(clazz, c -> {
            List<Field> result = new ArrayList<>();
            for (Field f : c.getDeclaredFields()) {
                if (f.isAnnotationPresent(User.Column.class)) result.add(f);
            }
            return result;
        });
    }

    // ── Type-safe column reader ────────────────────────────────────────────────
    /**
     * Reads a column from ResultSet and casts it to the correct Java type.
     * Handles: String, int/Integer, long/Long, boolean/Boolean, LocalDateTime, Enum.
     */
    private static Object readColumn(ResultSet rs, String col, Class<?> type) throws SQLException {
        if (type == String.class)                    return rs.getString(col);
        if (type == int.class || type == Integer.class) return rs.getInt(col);
        if (type == long.class || type == Long.class)   return rs.getLong(col);
        if (type == boolean.class || type == Boolean.class) return rs.getBoolean(col);
        if (type == double.class || type == Double.class)   return rs.getDouble(col);
        if (type == LocalDateTime.class) {
            Timestamp ts = rs.getTimestamp(col);
            return ts != null ? ts.toLocalDateTime() : null;
        }
        if (type.isEnum()) {
            String val = rs.getString(col);
            if (val == null) return null;
            @SuppressWarnings("unchecked")
            Object e = Enum.valueOf((Class<Enum>) type, val);
            return e;
        }
        return rs.getObject(col);
    }
}